# Generated by Django 3.1.7 on 2021-03-30 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
