# Generated by Django 3.0 on 2021-03-31 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university_app', '0002_class_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='num',
            field=models.PositiveSmallIntegerField(unique=True),
        ),
    ]
