# Generated by Django 3.0 on 2021-03-31 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university_app', '0003_auto_20210331_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='university_app.Department'),
        ),
    ]
