# Generated by Django 3.0 on 2021-03-31 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university_app', '0005_auto_20210331_1238'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='class',
            unique_together={('num', 'department')},
        ),
    ]
