# Generated by Django 3.0 on 2021-03-31 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university_app', '0006_auto_20210331_1336'),
        ('course_app', '0002_auto_20210331_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='desc',
        ),
        migrations.AddField(
            model_name='course',
            name='co_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='university_app.Class'),
        ),
    ]
